---  
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  tasks:
    - name: list users
      shell: "cut -d: -f1 /etc/passwd"
      register: users
    
    - name: prints out list of users
      debug: var=users.stdout_lines
